title: Byeongchang Kim
subtitle: (김병창, @bckim92)
face: /assets/img/byeongchang.jpg
cv: https://drive.google.com/open?id=1F7MZsD-iwhFz8DN0bYuW8SMkeADGRj3H
description: Ph.D student in CSE at Seoul National University
location: Seoul, Korea
email: byeongchang.kim AT vision.snu.ac.kr
homepage: https://bckim92.github.io
twitter: https://twitter.com/ByeongchangKim
github: https://github.com/bckim92
linkedin: https://www.linkedin.com/in/byeongchang-kim-64b3b9123/
google_analytics: UA-146496389-1
theme: jekyll-theme-minimal
google_scholar: https://scholar.google.com/citations?hl=ko&user=O23D9m8AAAAJ
semantic_scholar: https://www.semanticscholar.org/author/Byeongchang-Kim/3231991
